apiVersion: v1
kind: ConfigMap
metadata:
  name: temporal-config
  namespace: temporal
data:
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_DATABASE: "temporal"
  DB_VISIBILITY_DATABASE: "temporal_visibility"
  TEMPORAL_ADDRESS: "temporal:7233"
